export default {
  CHANGE_TASK: 'CHANGE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  ADD_TASK: 'ADD_TASK',
  SET_CURRENT_TASK: 'SET_CURRENT_TASK',
  SET_CURRENT_TODO: 'SET_CURRENT_TODO',
  SHOW_POPUP: 'SHOW_POPUP',
  CREATE_TODO: 'CREATE_TODO',
  PUSH_NOTIFICATION: 'PUSH_NOTIFICATION',
  CHANGE_TODO: 'CHANGE_TODO',
  REMOVE_TODO: 'REMOVE_TODO',
  ADD_TASK_FOR_CHANGE_WINDOW: 'ADD_TASK_FOR_CHANGE_WINDOW',
  CLEAR_OBJ_OF_TASKS: 'CLEAR_OBJ_OF_TASKS',
  LOAD_LOCAL_STORAGE: 'LOAD_LOCAL_STORAGE',
  SWITCH_PRELOADER: 'SWITCH_PRELOADER',
  SET_TOKEN: 'SET_TOKEN'
}